version: '2'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
    - mongo
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  app:
    image: seannicholson/backend 
    ports:
      - "5000:5000"
    depends_on:
    - mongo
    env_file:
    - docker.env
    volumes:
      - file-volume:/temp

  sftp-server:
    build:
      context: ./sftp
      args:
        SSH_MASTER_USER: ${SSH_MASTER_USER}
        SSH_MASTER_PASS: ${SSH_MASTER_PASS}
    hostname: server
    ports:
      - "2222:22"
    volumes:
      - file-volume:/uploads
    env_file:
      - docker.env

  file-volume:
    container_name: file-volume
    volumes:
      - ./Docker/AppConf:/var/www/conf

volumes:
  file-volume:

