version: '2'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
    - mongo
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  app:
    image: seannicholson/backend 
    ports:
      - "5000:5000"
    depends_on:
    - mongo
    env_file:
    - docker.env
    volumes:
      - file-volume:/temp

  sftp-server:
    build:
      context: ./sftp
      args:
        SSH_MASTER_USER: master
        SSH_MASTER_PASS: master
    hostname: server
    ports:
      - "2222:22"
    volumes:
      - file-volume:/uploads
    environment:
      SSH_MASTER_USER: master
      SSH_MASTER_PASS: master

volumes:
  file-volume:
